services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Fixtures\:
        resource: '../tests/Fixtures/*'

    test.doctrine.fixtures.loader: '@doctrine.fixtures.loader'
